Container2020/edition2020/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('web.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Container2020/web/urls.py
from django.urls import path
from web import views

# Specifying the path below:

urlpatterns =[
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('subscribe', views.subscribe, name='subscribe'),
    path('sites', views.sites, name='sites'),
    path('add_site', views.add_site, name='add_site'),
    path('delete_site/<str:pk>', views.delete_site, name='delete_site'),
    path('edit_site/<str:pk>', views.edit_site, name='edit_site'),
    path('all_sites_delete', views.all_sites_delete, name='all_sites_delete'),
    #This one is for fun:
    path('feedback', views.feedback, name='feedback'),
    #Lesson URL:
    path('lessons', views.lessons, name='lessons'),
    # send mail url:
    path('send_mail', views.send_mail, name='send_mail'),
    # add_service URL:
    path('add_service', views.add_service, name='add_service'),
    #edit_service URL:
    path('edit_service/<str:pk>', views.edit_service, name='edit_service'),
    # delete_service URL:
    path('delete_service/<str:pk>', views.delete_service, name='delete_service'),
    # add_type URL:
    path('add_type', views.add_type, name='add_type'),
    #edit_type URL:
    path('edit_type/<str:pk>', views.edit_type, name='edit_type'),
    #delete_type URL:
    path('delete_type/<str:pk>', views.delete_type, name='delete_type'),
    # Expense URL:
    path('expense', views.expense, name='expense'),
    # load_types_url URL:
    path('load_types_url', views.load_types_url, name='load_types_url'),
    # view expense URL:
    path('view_expense', views.view_expense, name='view_expense'),
    #Query Expense URL:
    path('query_expense', views.query_expense, name='query_expense'),
    #total_types URL:
    path('total_types', views.total_types, name='total_types'),
    #percentage URL:
    path('percentage', views.percentage, name='percentage'),
    # edit Expense URL:
    path('edit_expense/<str:pk>', views.edit_expense, name='edit_expense'),
    #delete expense URL:
    path('delete_expense/<str:pk>', views.delete_expense, name='delete_expense'),
    # login_note URL:
    path('login_note', views.login_note, name='login_note'),
    #adding an extra one to see if it will work or not:
    path('view_types/<str:pk>', views.view_types, name='view_types'),
    #adding daily_expenses to see the current daily transactions:
    path('daily_expenses', views.daily_expenses, name='daily_expenses'),
    #adding daily_expenses_delete URL:
    path('daily_expense_delete/<str:pk>', views.daily_expense_delete, name='daily_expense_delete'),
]

Container2020/web/models.py
from django.db import models

# Create your models here.

# This is the Sites Model for sharing:
class Site(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, unique=True, verbose_name="Enter Title")
    description = models.TextField(null=False, blank=False, unique=True, verbose_name="Enter Description")
    url = models.URLField(null=False, blank=False, unique=True, verbose_name="Website URL")
    image = models.ImageField(null=False, blank=False, verbose_name="Upload Image")

    class Meta:
        unique_together=[['title', 'url']]
    def __str__(self):
        return self.title
class Service(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, unique=True)

    def __str__(self):
        return self.name

class Type(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, verbose_name='Choose Service')
    name = models.CharField(max_length=200, null=False, blank=False, unique=False, verbose_name="Add Type")
    description = models.CharField(max_length=1000, null=True, blank=True, verbose_name="Description")
    entry_date = models.DateField(auto_now_add=True, null=False, blank=False)

    class Meta:
        unique_together=[['service', 'name']]

    def __str__(self):
        return self.name

class Payment(models.Model):
    name = models.CharField(max_length=200, null=False, blank=False, verbose_name="Enter Payment Method")
    entry_date  = models.DateTimeField(auto_now_add=True, null=False, blank=False)

    def __str__(self):
        return self.name

class Expense(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='service', verbose_name="Choose Service")
    type = models.ForeignKey(Type, on_delete=models.CASCADE, related_name='type', verbose_name="Choose Type")
    payment = models.ForeignKey(Payment, on_delete=models.CASCADE, related_name='payment', verbose_name="Payment Method")
    amount = models.FloatField(null=False, blank=False)
    remark = models.TextField(null=True, blank=True, verbose_name="Notes")
    entry_date = models.DateTimeField(auto_now_add=True)
    only_date = models.DateField(auto_now_add=True)


    def __str__(self):
        return str(self.service.name)+'  '+str(self.type.name)+'  '+ str(self.entry_date)

class Feedback(models.Model):
    name  = models.CharField(max_length=200, verbose_name="Title", null=False, blank=False)
    email = models.EmailField(null=False, blank=False, verbose_name="E-Mail Address")
    message = models.TextField(null=False, blank=False, verbose_name="Message")
    entry_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name +"  "+ str(self.entry_date)

Container2020/templates/pages/add_service.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
    Adding Service Page
{% endblock title %}

{% block content %}
<style>
    .btn_service {
        background-color:none;
    }
    .btn_service:hover{
        background-color:bisque;
        color:red;
        border-radius:4px solid bisque;

    }
</style>
<div class="container">
    <!--{% for message in messages %}-->
    <!--<div class="alert alert-warning">-->
    <!--    {{message}}-->
    <!--</div>-->
    <!--{% endfor %}-->

    <div class="card">
        <div class="card-header"  style="background-color:blanchedalmond">
            <b> Add Service</b>
        </div>
        <div class="card-body" style="border:2px solid blanchedalmond">
            <div>
            <!--<div class="table">-->
                <form action="" method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <span class="fa-stack fa-lg">
                        <button type="submit" class="btn">

                            <i class="fa fa-circle-o-notch fa-stack-5x fa-spin"></i>
                            <i class="fa fa-save fa-2x"></i>
                        </button>
                    </span>


                    <button type="reset" class="btn" style="float:right;">
                        <i class="fa fa-refresh fa-2x"></i>
                    </button>


                </form>
            </div>
        </div>
        </div>
        <hr>
        {% if services %}
        <div>
        <table class="table" style="background-color:white">
            <thead>
              <tr style="background-color:bisque;">
                    <th scope="col"><b>ID</b></th>
                    <th scope="col"><b>Service</b></th>
                    <th scope="col"><b>ViewTypes</b></th>
                    <th scope="col"><b>Edit</b></th>
                    <th scope="col"><b>Delete</b></th>

              </tr>
            </thead>
            {% for service in services %}
            <tbody>
              <tr>
                <th scope="row">{{service.id}}</th>
                <td>{{service.name}}</td>
                <!-- We are using font awsome below from the active online link for the first time -->
                <td><a href="{% url 'view_types' service.id %}" class="btn"><i class="fa fa-eye fa-lg"></i></a></td>
                <td><a href="{% url 'edit_service' service.id %}" class="btn"><i class="fa fa-pencil fa-lg"></i></a></td>
                <td><a href="#" class="btn"><i class="fa fa-trash fa-lg"></i></a></td>
                <!-- Delete link is deactivate: {% url 'delete_service' service.id %}-->
              </tr>
            </tbody>
            {% endfor %}


          </table>
        </div>
          {% endif %}

</div>

{% endblock content %}

Container2020/templates/pages/add_site.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card" style="border:2px solid bisque;">
        <div class="card-header" style="background-color:bisque;">
            <h3 style="color:black">Add a New Site</h3>
        </div>

        <div class="card-body">
        <div class="container">
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn">
                <i class="fa fa-save fa-2x"></i>
            </button>
            <!-- Setting the reset button of this page using font awsome fa-refresh to overwrite the stylesheet used on this website-->
            <button type="reset" class="btn" style="float:right;">
                <i class="fa fa-refresh fa-2x"></i>
            </button>
        </form>
    </div>

</div>
</div>
</div>


{% endblock content %}

Container2020/templates/pages/add_type.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<style>
    .save_button, .reset_button {
    background-color:bisque;
    color:black;
    border-radius:10px;



    }
    .save_button:hover{
        background-color: greenyellow;
        color: black;
        transition: 2s;
        padding-right:5px;

    }
    .reset_button:hover{
        background-color:red;
        color:black;
        transition: 2s;
        padding-right:5px;
    }
</style>

<div class="container">

    <div class="container">
            <!--{% for message in messages %}-->
            <!--<div class="alert alert-success">-->
            <!--    {{message}}  <i class="fa fa-thumbs-up fa-lg" style="color:green"></i>-->
            <!--</div>-->
            <!--{% endfor %}-->
            <div>
                <div class="card">
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="card-header" style="background-color:bisque">
                            Add Type
                        </div>
                        <div class="card-body">
                            {{form|crispy}}
                        </div>
                        <div class="card-footer" style="background-color:bisque">
                            <button type="submit" class="btn">
                                <i class="fa fa-save fa-2x" style="color:green;"></i>
                            </button>
                            <button type="reset" class="btn" style="float:right">
                                <i class="fa fa-refresh fa-spin fa-2x" style="color:red;"></i>
                            </button>
                        </div>


                    </form>
                </div>

            </div>

</div>

<!-- Adding a script that allows autofocus on service_id when loading the page:-->
<script>
    $(document).ready(function(){
        window.onload=function(){
            $(`#id_service`).focus();
        }
    })
</script>

{% endblock content %}

Container2020/templates/pages/calculator.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="container">
        {% for message in messages %}
        <div class="alert alert-info" style="color:brown; border:2px; border-radius:2px">
            {{message}}
        </div>
        {% endfor %}
        
            <div>
                
            <form action="" method="POST">
                {% csrf_token %}
                <div class="card">
                    <div class="card-header">
                        <b>Simple Calculator</b>
                    </div>
                    <div class="card-body">
                        <strong>Enter First Number</strong>
                        <br>
                        <input type="text" name="number1" placeholder="">
                        <br>
                        <strong>Enter Second Number</strong>
                        <br>
                        <input type="text" name="number2" placeholder="">
                                
                        <select name="operation" >
                            <option value="Addition">Addition</option>
                            <option value="Subtraction">Subtraction</option>
                            <option value="Multiplication">Multiplication</option>
                            <option value="Division">Division</option>
                        </select>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-sm btn-outline-success">Calculate</button>
                    </div>
                    
                        
                    
                </form>
        </div>
        </div>
        
    </div>
</div>

{% endblock content %}

Container2020/templates/pages/daily_expenses.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}
<!--
    This is the page for displaying the records saved daily for expense without
    having to inquire the whole table using data. A way of saving time to view
    directly by signing in and then, clicking the button 'Daily Expense'
 -->

 <!-- Setting the Sweet Alert to delete the record chosen: -->



{% block content %}
<div class="container">
    <div class="alert alert-warning" style="box-shadow: 3px 3px 3px 3px; color:brown; text-align:center; border-radius:50px; font-weight:bold;">
        <h4 style="color:brown;">
            Viewing The daily Expenses

        </h4>
        <p>
        <h5 style="color:darkgreen;">{{today}}</h5>
        </p>
        <p style="box-shadow:3px 3px 3px 3px; background-color:bisque; color:red; border-radius:15px;">
            {% if total_amount %}
            Amount: {{total_amount}} OMR
            {% else %}
            Amount: 0.000 OMR
            {% endif %}
        </p>
    </div>
    <div style="overflow-x: auto;">
        {% if dict_expenses %}
        <table class="table" style="border:2px solid black;">
            <thead>
                <tr style="background-color:bisque;">
                    <th>#</th>
                    <th>Service</th>
                    <th>Type</th>
                    <th>Amount</th>
                    <th>Payment</th>
                    <th>View</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            {% for key, value in dict_expenses.items %}
            <tbody>
                {% if value.2 >= 15 %}

                <tr style="color:darkred; font-weight:bold; background-color:black;">
                    <td>{{key}}</td>
                    <td>{{value.0}}</td>
                    <td>{{value.1}}</td>
                    <td>{{value.2}}</td>
                    <td>{{value.3}}</td>
                    <td>
                        <button id="display_note" onclick="ShowNote(this)" value="{{value.4}}" class="btn-sm btn-outline-danger" style="background-color: red; width:auto; height:40px;">
                            <i class="fa fa-eye fa-lg"></i>
                        </button>
                    </td>
                    <td>
                        <a href="{% url 'edit_expense' value.5 %}" class="btn-sm"><i class="fa fa-pencil fa-lg" style="color:red;"></i></a>
                    </td>
                    <td>
                        <a href="#" onclick="DeleteExpense({{value.5}})" class="btn-sm"><i class="fa fa-trash fa-lg" style="color:red;"></i></a>
                    </td>

                </tr>
                {% elif value.2 >= 5 and value.2 <= 15 %}
                <tr style="color:#d9b51c; font-weight:bold; background-color:black;">
                    <td>{{key}}</td>
                    <td>{{value.0}}</td>
                    <td>{{value.1}}</td>
                    <td>{{value.2}}</td>
                    <td>{{value.3}}</td>
                    <td>
                        <button id="display_note" onclick="ShowNote(this)" value="{{value.4}}" class="btn-sm btn-outline-warning" style="background-color: orange; width:auto; height:40px;">
                            <i class="fa fa-eye fa-lg"></i>
                        </button>
                    </td>
                    <td>
                        <a href="{% url 'edit_expense' value.5 %}" class="btn-sm"><i class="fa fa-pencil fa-lg" style="color:orange;"></i></a>
                    </td>
                    <td>
                        <a href="#" onclick="DeleteExpense({{value.5}})" class="btn-sm" style="color:orange;"><i class="fa fa-trash fa-lg" style="color:orange;"></i></a>
                    </td>

                </tr>
                {% else %}
                <tr style="color:black; color:darkgreen;">
                    <td>{{key}}</td>
                    <td>{{value.0}}</td>
                    <td>{{value.1}}</td>
                    <td>{{value.2}}</td>
                    <td>{{value.3}}</td>
                    <td>
                        <button id="display_note" onclick="ShowNote(this)" value="{{value.4}}" class="btn-sm btn-outline-success" style="background-color: lightgreen; width:auto; height:40px;">
                            <i class="fa fa-eye fa-lg"></i>
                        </button>
                    </td>
                    <td>
                        <a href="{% url 'edit_expense' value.5 %}" class="btn-sm"><i class="fa fa-pencil fa-lg" style="color:lightgreen;"></i></a>
                    </td>
                    <td>
                        <a href="#" onclick="DeleteExpense({{value.5}})" class="btn-sm"><i class="fa fa-trash fa-lg" style="color:lightgreen;"></i></a>
                    </td>
                </tr>
                {% endif %}

            </tbody>
            {% endfor %}

        </table>
        {% else %}
        <div class="alert alert-warning" style="text-align: center;  border-radius:15px; color:brown;">
            <h5 style="box-shadow:5px 5px 5px 5px; color:blue; border-radius:15px;">
                No Expenses saved for today
            </h5>
        </div>
        {% endif %}
    </div>
</div>




<!-- Using the following function to create a sweet alert 2 js to delete a record: -->
<script>
    function DeleteExpense(id){
        Swal.fire({
            'title': 'Delete Expense',
            'text': 'Are you sure you want to delete',
            'icon': 'warning',
            'showCancelButton': true,
            'cancelButtonText': 'No, Abort',
            'confirmButtonText': 'Yes, Delete',
        })
        .then(function(result){
            if(result.isConfirmed){
                window.location.href="/daily_expense_delete/"+id
            }
        })
    }

    //Testing to see if we can manage to display the note in sweet alert or not:
    function ShowNote(b){
        const note = b.value
        if(note.length >0){
            Swal.fire({
            title: 'Remarks',
            text: note,
            icon: 'success',
            confirmButtonColor: 'Green'
        })

        }
        else{
            Swal.fire({
            title: 'Remarks',
            text: 'This record does not have a note or remark',
            icon: 'error',
            confirmButtonColor: 'red'
            })
        }

    }



</script>
{% endblock content %}

Container2020/templates/pages/edit_service.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <div class="card">
        <div class="card-header" style="background-color:bisque">
            <h4>Edit Service Name</h4>
        </div>
        <form action="" method="POST">
        <div class="card-body">
                    {% csrf_token %}
                    {{form|crispy}}



        </div>
        <div class="card-footer" style="background-color:lightblue;">
            <button type="submit" class="btn btn-default">
                <i class="fa fa-edit fa-lg fa-spin" style="color:green;"></i>
                Update
            </button>

        </div>
        </form>

    </div>

</div>
{% endblock content %}

Container2020/templates/pages/login.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <!--{% for message in messages %}-->
    <!--<div class="alert alert-warning">-->
    <!--    {{message}}-->
    <!--</div>-->
    <!--{% endfor %}-->
    <div class="wrapper fadeInDown">
        <div id="formContent">
          <!-- Tabs Titles -->

          <!-- Icon -->
          <div class="fadeIn first">
            <img src="{% static 'icons/login.ico' %}" id="icon" alt="User Icon" />
          </div>

          <!-- Login Form -->
          <form method="POST" action="">
              {% csrf_token %}
            <input type="text" id="login" class="fadeIn second" name="username" placeholder="Username" autofocus>
            <input type="password" id="password" class="fadeIn third" name="password" placeholder="Password">
            <input type="submit" class="btn btn-outline-primary" value="Log In">
          </form>


        </div>
      </div>
</div>

{% endblock content %}

Container2020/templates/pages/percentage.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}



<div class="container">
    <!--{% for message in messages %}-->
    <!--<div class="alert alert-warning">-->
    <!--    {{message}}-->
    <!--</div>-->
    <!--{% endfor %}-->
    <div class="card">
        <div class="card-header" style="background-color:bisque;">
            <h4>Showing Percentage Based on Two Dates:</h4>
            <hr>
        </div>
        <form method="POST" action="">
        <div class="card-body">
            {% csrf_token %}
            {{form|crispy}}
        </div>
        <div class="card-footer" style="background-color:bisque;">
            <button type="submit" class="btn">
                <i class="fa fa-question-circle fa-2x" style="color:red;"></i>
            </button>
            <button type="reset" class="btn" style="float:right">
                <i class="fa fa-refresh fa-spin fa-2x" style="color:red;"></i>
            </button>
        </div>
        </form>
    </div>

    <!-- Starting the code of displaying the data from here-->
    {% if percentages %}
    <div class="alert alert-warning d-flex justify-content-left" style="border:2px dotted red;">
    <b>
        <b>Percentage of Type Items:</b>
        <br>
        <b>From </b> <b style="color:red">{{from_date}}</b>

        <b>Until </b><b style="color:red">{{to_date}}</b>
        <br>
        <b>Full Amount: {{full_total}}</b>
    </b>


    <hr>
    </div>
    <div style="overflow-x: auto; border:2px solid bisque">
        <table class="table">
            <tr style="background-color:bisque; border:2px solid bisque; border-radius: 2px solid bisque">
                <th><b>Type Name</b></th>
                <th><b>Percentage</b></th>

            </tr>
            <tr>
            {% for key, value in percentages.items %}
                <td>{{key}}</td>
                <td>{{value}} %</td>
            </tr>
            {% endfor %}
        </table>

    </div>

    {% endif %}


</div>

{% endblock content %}

Container2020/templates/pages/query_expense.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

<!-- This page is for querying the expenses based on the start and end dates -->
<!-- Please make sure to keep it as a reference for future use -->
{% block content %}

<div class="container">


    <form action="" method="POST">
        {% csrf_token %}
        <div class="card" style="border:2px solid bisque">
            <div class="card-header" style="background-color:bisque; color: black;">
                <b> Querying The Expense Table Between Specified Dates:</b>
                <hr>
            </div>
            <div class="card-body">
                {{form|crispy}} <!--   this is the modification goes here  -->
            </div>

            <div class="card-footer" style="background-color:bisque; color: black;">
                <button type="submit" class="btn">
                    <i class="fa fa-question-circle fa-2x"></i>
                </button>
                <button type="reset" class="btn" style="float:right">
                    <i class="fa fa-refresh fa-2x"></i>
                </button>

            </div>


        </div>
    </form>
    <!----this is the for loop for displaying messages-->
    {% for message in messages %}
    <div class="alert alert-warning" style="border:2px dotted bisque">
        <b>
            {{message}}
        </b>

        {% if total_expenses %}
        <hr>
        <div class="alert alert-warning" style="border:2px dotted red">
        <b> Total Records: <b style="color:red">{{total_expenses}}</b></b>
        <br>
        <b> Total Amount : <b style="color:red">{{amount_spent}} OMR</b></b>
        {% endif %}
        </div>
    {% endfor %}
    </div>
    <div>
            {% if expenses %}
            <div style="overflow-x: auto; border:2px solid bisque">
                <table class="table">
                    <thead>
                    <tr style="background-color:bisque;">
                        <th><b>Date</b></th>
                        <th><b>Service</b></th>
                        <th><b>Type</b></th>
                        <th><b>Payment</b></th>
                        <th><b>Amount</b></th>
                        <th><b>View</b></th>
                        <th><b>Edit</b></th>
                    </tr>
                    </thead>
                    {% for expense in expenses %}
                    <tbody>
                        {% if expense.amount >= 50 %}
                            <tr style="background-color:#ff595e; font-weight:bold; color:darkred;">
                                <td>{{expense.only_date}}</td>
                                <td>{{expense.service}}</td>
                                <td>{{expense.type.name}}</td>
                                <td>{{expense.payment.name}}</td>
                                <td>{{expense.amount}}</td>
                                <td>
                                    <button class="btn-sm btn-outline-danger" value="{{expense.remark}}" id="view_note" onclick="viewNote(this)" style="height:40px;">
                                    <i class="fa fa-eye"></i>
                                    </button>
                                </td>
                                <td><a href="{% url 'edit_expense' expense.id %}" class="btn"><i class="fa fa-pencil"></i></a></td>
                            </tr>
                        {% elif expense.amount >= 10  %}
                            <tr style="background-color:orange; font-weight:bold;">
                                <td>{{expense.only_date}}</td>
                                <td>{{expense.service}}</td>
                                <td>{{expense.type.name}}</td>
                                <td>{{expense.payment.name}}</td>
                                <td>{{expense.amount}}</td>
                                <td>
                                    <button class="btn-sm btn-outline-warning" value="{{expense.remark}}" id="view_note" onclick="viewNote(this)" style="height:40px;">
                                    <i class="fa fa-eye"></i>
                                    </button>
                                </td>
                                <td><a href="{% url 'edit_expense' expense.id %}" class="btn"><i class="fa fa-pencil"></i></a></td>
                            </tr>
                        {% elif expense.amount < 10 and expense.amount >= 5 %}
                            <tr style="background-color:#fdfae5; font-weight:bold;">
                                <td>{{expense.only_date}}</td>
                                <td>{{expense.service}}</td>
                                <td>{{expense.type.name}}</td>
                                <td>{{expense.payment.name}}</td>
                                <td>{{expense.amount}}</td>
                                <td>
                                    <button class="btn-sm btn-outline-primary" value="{{expense.remark}}" id="view_note" onclick="viewNote(this)" style="height:40px;">
                                    <i class="fa fa-eye"></i>
                                    </button>
                                </td>
                                <td><a href="{% url 'edit_expense' expense.id %}" class="btn"><i class="fa fa-pencil"></i></a></td>
                            </tr>

                        {% else %}
                            <tr style="background-color:#f1f8e9;">
                                <td>{{expense.only_date}}</td>
                                <td>{{expense.service}}</td>
                                <td>{{expense.type.name}}</td>
                                <td>{{expense.payment.name}}</td>
                                <td>{{expense.amount}}</td>
                                <td>
                                    <button class="btn-sm btn-outline-success" value="{{expense.remark}}" id="view_note" onclick="viewNote(this)" style="height:40px;">
                                    <i class="fa fa-eye"></i>
                                    </button>
                                </td>
                                <td><a href="{% url 'edit_expense' expense.id %}" class="btn"><i class="fa fa-pencil"></i></a></td>
                            </tr>
                        {% endif %}

                    </tbody>
                    {% endfor  %}
                </table>

        {% endif %}
    </div>


<!-- Viewing the content of the remark for each record through using a button-->
<script>
    function viewNote(x){
        const note = document.querySelector("#view_note")
        if((x.value).length>0)
        {
            Swal.fire({
                title: "Expense Details",
                text: x.value,
                icon: "success"
            })
        }
        else
        {
            Swal.fire({
                title: "Empty",
                text: "No Notes recorded for this expense",
                icon: "error",
                confirmButtonColor: "red"
            })
        }
    }
</script>


{% endblock content %}